<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class VarietasKedelaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil ID dari tabel org_pen_tan secara dinamis
        $balitkabiId = DB::table('org_pen_tan')->where('nama_opt', 'Balitkabi')->value('id');
        
        // Pastikan ID ditemukan sebelum menyisipkan data
        if (!$balitkabiId) {
            echo "Warning: Seeder OrgPenTan belum dijalankan atau data 'Balitkabi' tidak ditemukan. Melewatkan seeding VarietasKedelai.\n";
            return;
        }

        $varietasKedelai = [
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Anjasmoro',
                'tahun' => '1993',
                'sk' => '197/Kpts/TP.240/1/1993',
                'galur' => 'Galur B-3030',
                'asal' => 'Indonesia (galur persilangan)',
                'potensi_hasil' => 2.50,
                'rata_hasil' => 1.80,
                'umur_berbunga' => '±30 HST',
                'umur_masak' => '±87 hari',
                'tinggi_tanaman' => '85–90 cm',
                'warna_biji' => 'kuning',
                'bobot' => '13 g/100 biji',
                'kadar_protein' => 38.00,
                'kadar_lemak' => 17.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_anjasmoro.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Argomulyo',
                'tahun' => '1994',
                'sk' => '200/Kpts/TP.240/1/1994',
                'galur' => 'Galur G 426 H / G-2400 H',
                'asal' => 'Persilangan (Orba × IAC-2)',
                'potensi_hasil' => 2.40,
                'rata_hasil' => 1.70,
                'umur_berbunga' => '±33 HST',
                'umur_masak' => '±83 hari',
                'tinggi_tanaman' => '80–85 cm',
                'warna_biji' => 'kuning',
                'bobot' => '14 g/100 biji',
                'kadar_protein' => 39.50,
                'kadar_lemak' => 17.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_argomulyo.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Grobogan',
                'tahun' => '2008',
                'sk' => '321/Kpts/SR.120/8/2008',
                'galur' => 'B3217-1-4-1',
                'asal' => 'Persilangan (Malabar × S 398)',
                'potensi_hasil' => 3.00,
                'rata_hasil' => 2.00,
                'umur_berbunga' => '±33 HST',
                'umur_masak' => '±78 hari',
                'tinggi_tanaman' => '50–60 cm',
                'warna_biji' => 'kuning',
                'bobot' => '15.5 g/100 biji',
                'kadar_protein' => 42.92,
                'kadar_lemak' => 17.65,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_grobogan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Wilis',
                'tahun' => '1985',
                'sk' => '450/Kpts/TP.240/9/1985',
                'galur' => 'Galur No. 222',
                'asal' => 'Persilangan (Orba × IAC-2)',
                'potensi_hasil' => 2.80,
                'rata_hasil' => 1.90,
                'umur_berbunga' => '±35 HST',
                'umur_masak' => '±88 hari',
                'tinggi_tanaman' => '85–95 cm',
                'warna_biji' => 'kuning',
                'bobot' => '12 g/100 biji',
                'kadar_protein' => 38.00,
                'kadar_lemak' => 17.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_wilis.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Dering-2',
                'tahun' => '2011',
                'sk' => '246/Kpts/SR.120/3/2011',
                'galur' => 'Dering-2 (Derawan × Rapa)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 2.90,
                'rata_hasil' => 2.10,
                'umur_berbunga' => '±35 HST',
                'umur_masak' => '±85 hari',
                'tinggi_tanaman' => '80–90 cm',
                'warna_biji' => 'kuning',
                'bobot' => '13.5 g/100 biji',
                'kadar_protein' => 40.00,
                'kadar_lemak' => 17.20,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_dering2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Dega-1',
                'tahun' => '2017',
                'sk' => '114/Kpts/SR.120/D.2.7/2017',
                'galur' => 'Dega-1 (Dering-1 × Galunggung)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 3.50,
                'rata_hasil' => 2.50,
                'umur_berbunga' => '±32 HST',
                'umur_masak' => '±80 hari',
                'tinggi_tanaman' => '65–75 cm',
                'warna_biji' => 'kuning',
                'bobot' => '14 g/100 biji',
                'kadar_protein' => 41.50,
                'kadar_lemak' => 18.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_dega1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Deja-1',
                'tahun' => '2017',
                'sk' => '114/Kpts/SR.120/D.2.7/2017',
                'galur' => 'Deja-1 (Dering-1 × Anjasmoro)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 3.40,
                'rata_hasil' => 2.40,
                'umur_berbunga' => '±31 HST',
                'umur_masak' => '±79 hari',
                'tinggi_tanaman' => '60–70 cm',
                'warna_biji' => 'kuning',
                'bobot' => '15 g/100 biji',
                'kadar_protein' => 41.00,
                'kadar_lemak' => 17.80,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_deja1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Demas-1',
                'tahun' => '2016',
                'sk' => '211/Kpts/SR.120/D.2.7/2016',
                'galur' => 'Demas-1 (Detam-1 × Argomulyo)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 3.20,
                'rata_hasil' => 2.30,
                'umur_berbunga' => '±30 HST',
                'umur_masak' => '±78 hari',
                'tinggi_tanaman' => '65–75 cm',
                'warna_biji' => 'kuning',
                'bobot' => '16 g/100 biji',
                'kadar_protein' => 40.50,
                'kadar_lemak' => 17.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_demas1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Denasa-1',
                'tahun' => '2018',
                'sk' => '120/Kpts/SR.120/D.2.7/2018',
                'galur' => 'Denasa-1 (Dering-1 × Nanti-1)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 3.60,
                'rata_hasil' => 2.60,
                'umur_berbunga' => '±33 HST',
                'umur_masak' => '±82 hari',
                'tinggi_tanaman' => '70–80 cm',
                'warna_biji' => 'kuning',
                'bobot' => '15.5 g/100 biji',
                'kadar_protein' => 42.00,
                'kadar_lemak' => 18.20,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_denasa1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Derap-1',
                'tahun' => '2016',
                'sk' => '211/Kpts/SR.120/D.2.7/2016',
                'galur' => 'Derap-1 (Detam-1 × Argomulyo)',
                'asal' => 'Persilangan',
                'potensi_hasil' => 3.20,
                'rata_hasil' => 2.30,
                'umur_berbunga' => '±30 HST',
                'umur_masak' => '±78 hari',
                'tinggi_tanaman' => '65–75 cm',
                'warna_biji' => 'kuning',
                'bobot' => '16 g/100 biji',
                'kadar_protein' => 40.50,
                'kadar_lemak' => 17.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_derap1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('varietas_kedelai')->insert($varietasKedelai);
    }
}