<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class VarietasKacangTanahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Ambil ID dari tabel org_pen_tan secara dinamis
        $balitkabiId = DB::table('org_pen_tan')->where('nama_opt', 'Balitkabi')->value('id');
        
        // Pastikan ID ditemukan sebelum menyisipkan data
        if (!$balitkabiId) {
            echo "Warning: Seeder OrgPenTan belum dijalankan atau data 'Balitkabi' tidak ditemukan. Melewatkan seeding VarietasKacangTanah.\n";
            return;
        }

        $varietasKacangTanah = [
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Jerapah',
                'tahun' => '2007',
                'sk' => '134/Kpts/SR.120/2/2007',
                'galur' => 'No.165',
                'asal' => 'Seleksi',
                'potensi_hasil' => 2.50,
                'rata_hasil' => 1.80,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±90 hari',
                'tinggi_tanaman' => '45–50 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '40 g/100 biji',
                'kadar_protein' => 26.00,
                'kadar_lemak' => 48.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_jerapah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Anoa',
                'tahun' => '2007',
                'sk' => '134/Kpts/SR.120/2/2007',
                'galur' => 'No.165',
                'asal' => 'Seleksi',
                'potensi_hasil' => 2.80,
                'rata_hasil' => 2.00,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±95 hari',
                'tinggi_tanaman' => '50–55 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '45 g/100 biji',
                'kadar_protein' => 27.00,
                'kadar_lemak' => 49.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_anoa.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Gajah',
                'tahun' => '1999',
                'sk' => '199/Kpts/SR.120/1999',
                'galur' => 'No.159',
                'asal' => 'Seleksi',
                'potensi_hasil' => 3.00,
                'rata_hasil' => 2.20,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±100 hari',
                'tinggi_tanaman' => '50–60 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '50 g/100 biji',
                'kadar_protein' => 28.00,
                'kadar_lemak' => 50.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_gajah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Bison',
                'tahun' => '2007',
                'sk' => '134/Kpts/SR.120/2/2007',
                'galur' => 'No.165',
                'asal' => 'Seleksi',
                'potensi_hasil' => 2.70,
                'rata_hasil' => 1.90,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±90 hari',
                'tinggi_tanaman' => '45–50 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '42 g/100 biji',
                'kadar_protein' => 26.50,
                'kadar_lemak' => 48.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_bison.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Garuda Dua',
                'tahun' => '2015',
                'sk' => '224/Kpts/SR.120/D.2.7/2015',
                'galur' => 'No.160',
                'asal' => 'Seleksi',
                'potensi_hasil' => 2.90,
                'rata_hasil' => 2.10,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±90 hari',
                'tinggi_tanaman' => '45–50 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '44 g/100 biji',
                'kadar_protein' => 27.50,
                'kadar_lemak' => 49.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_garuda_dua.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Garuda Tiga',
                'tahun' => '2015',
                'sk' => '224/Kpts/SR.120/D.2.7/2015',
                'galur' => 'No.161',
                'asal' => 'Seleksi',
                'potensi_hasil' => 3.10,
                'rata_hasil' => 2.30,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±95 hari',
                'tinggi_tanaman' => '50–55 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '48 g/100 biji',
                'kadar_protein' => 28.50,
                'kadar_lemak' => 50.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_garuda_tiga.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Domba',
                'tahun' => '2017',
                'sk' => '114/Kpts/SR.120/D.2.7/2017',
                'galur' => 'No.162',
                'asal' => 'Seleksi',
                'potensi_hasil' => 2.60,
                'rata_hasil' => 1.80,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±85 hari',
                'tinggi_tanaman' => '40–45 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '38 g/100 biji',
                'kadar_protein' => 25.50,
                'kadar_lemak' => 47.50,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_domba.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'org_pen_tan_id' => $balitkabiId,
                'nama_varietas' => 'Singa',
                'tahun' => '2017',
                'sk' => '114/Kpts/SR.120/D.2.7/2017',
                'galur' => 'No.163',
                'asal' => 'Seleksi',
                'potensi_hasil' => 3.20,
                'rata_hasil' => 2.40,
                'umur_berbunga' => '±25 HST',
                'umur_masak' => '±100 hari',
                'tinggi_tanaman' => '50–55 cm',
                'warna_biji' => 'merah muda',
                'bobot' => '46 g/100 biji',
                'kadar_protein' => 27.50,
                'kadar_lemak' => 49.00,
                'pengenal' => null,
                'inventor' => 'Balitkabi',
                'gambar' => 'placeholder_image_url_singa.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('varietas_kacang_tanah')->insert($varietasKacangTanah);
    }
}